### ISSUE TITLE
1.8 10 questions for tests db 

### ISSUE THREAD

**Issue by wszczawinski** [ISAKids4Ever/RecruitmentApp#24]

**Comment by MateuszRostkowski** [comment]
1. What HTML stands for
- Hyper Text Markup Language
- Hyper Text Markdown Language
- Home Tool Markup Language
- Hyperlinks and Text Markup Language

**Comment by MateuszRostkowski** [comment]
2. What is the correct HTML for creating a hyperlink?
-  ```<a name="http://www.intervyou.essa">IntervYou.essa</a>```
- ``` <a url="http://www.intervyou.essa">IntervYou.essa</a>```
- ``` <a>http://www.intervyou.essa</a>```
-  ```<a href="http://www.intervyou.essa">IntervYou</a>```

**Comment by MateuszRostkowski** [comment]
3. What is the correct HTML for inserting a background image?
- ```<body bg="background.gif">```
- ```<body style="background-image:url(background.gif)">```
- ```<background img="background.gif">```

**Comment by MateuszRostkowski** [comment]
4. An <iframe> is used to display a web page within a web page.
- False
- True
-  There is no such thing as an <iframe>

**Comment by MateuszRostkowski** [comment]
5. Choose the correct HTML element to define important text

- ```<b>```
- ```<important>```
- ```<strong>```
- ```<i>```

**Comment by MateuszRostkowski** [comment]
6. How can you open a link in a new tab/browser window? (3)
- ```<a href="url" target="new">```
- ``` <a href="url" new>```
- ``` <a href="url" target="_blank">```

**Comment by MateuszRostkowski** [comment]
7. How can you make a numbered list?(3)
- ```<dl>```
- ```<ul>```
- ```<ol>```
- ```<li>```

**Comment by MateuszRostkowski** [comment]
8. How can you make a bulleted list?(2)
- ```<ol>```
- ```<ul>```
- ```<dl>```
- ```<li>```

**Comment by MateuszRostkowski** [comment]
9. What is the correct HTML for making a drop-down list?(1)
- ``` <select>```
- ``` <input type="dropdown">```
- ``` <input type="select">```
- ``` <input type="list">```

**Comment by MateuszRostkowski** [comment]
10. Which input type defines a slider control?(3)
- ```<search>```
- ```<range>```
- ```<slider>```
- ```<controls>```
